---
name: wwwallet

include:
  # Services
  - path: ./components/caddy/compose.yaml
  - path: ./components/wallet-frontend/compose.yaml
  - path: ./components/wallet-backend/compose.yaml
  - path: ./components/wallet-issuer/compose.yaml
  - path: ./components/wallet-verifier/compose.yaml
  # Exporters
#  - path: ./components/wallet-exporters/backend-exporters.yaml
#  - path: ./components/wallet-exporters/issuer-exporters.yaml
#  - path: ./components/wallet-exporters/verifier-exporters.yaml
#  - path: ./components/wallet-exporters/metrics-scraper.yaml


