services:
  wallet-backend-db-exporter: &x-mysqld-exporter
    image: prom/mysqld-exporter:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9104:9104"
    depends_on:
      wallet-backend_db:
        condition: service_healthy
    command: ["--mysqld.address=${WALLET_BACKEND_DB_HOST:-wallet-backend_db}:3306", "--mysqld.username=${WALLET_BACKEND_USER:-wallet}"]
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${WALLET_BACKEND_PASSWORD:-wallet}
    networks:
      - wallet-backend_db_net
      - metrics_net

  wallet-issuer-db-exporter:
    <<: *x-mysqld-exporter
    ports:
      - "127.0.0.1:9105:9104"
    depends_on:
      wallet-issuer_db:
        condition: service_healthy
    command: ["--mysqld.address=${WALLET_ISSUER_DB_HOST:-wallet-issuer_db}:3306", "--mysqld.username=${WALLET_ISSUER_USER:-wallet}"]
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${WALLET_ISSUER_PASSWORD:-wallet}
    networks:
      - wallet-issuer_db_net
      - metrics_net

  wallet-verifier-db-exporter:
    <<: *x-mysqld-exporter
    ports:
      - "127.0.0.1:9106:9104"
    depends_on:
      wallet-verifier_db:
        condition: service_healthy
    command: ["--mysqld.address=${WALLET_VERIFIER_DB_HOST:-wallet-verifier_db}:3306", "--mysqld.username=${WALLET_VERIFIER_USER:-wallet}"]
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${WALLET_VERIFIER_PASSWORD:-wallet}
    networks:
      - wallet-verifier_db_net
      - metrics_net

networks:
  metrics_net:
    internal: true