---
services:
  wallet-frontend:
    build:
      context: ${WALLET_FRONTEND_BUILD_CONTEXT:-https://github.com/Didr/wallet-frontend.git#master-20251027-sirosid-sunet}
      dockerfile: Dockerfile
      # Note that changing the contents of a secret does not invalidate the docker build cache
      cache_from:
        - ghcr.io/sirosfoundation/wallet-frontend/cache:latest
      secrets:
        - wallet_frontend_envfile
      x-bake:
        no-cache-filter: # don't use cache for the step with secrets
          - builder
    restart: always
    ports:
      - 127.0.0.1:3000:3000

secrets:
  wallet_frontend_envfile:
    file: .env
